import {
  BarChart3,
  Bot,
  Bug,
  Crosshair,
  FileCheck,
  Fingerprint,
  Gauge,
  Globe,
  KeyRound,
  LayoutDashboard,
  MailWarning,
  MessageSquareLock,
  Network,
  ScanFace,
  Search,
  Share2,
  ShieldAlert,
  Siren,
  TrendingUp,
  Workflow,
  type LucideIcon,
} from "lucide-react";

export type ModuleGroup = "Operations" | "AI & Analysis" | "Toolkits" | "Business";

export interface ModuleMeta {
  id: string;
  label: string;
  description: string;
  route: string;
  icon: LucideIcon;
  shortcut?: string;
  group: ModuleGroup;
  phase: string;
  keywords: string[];
}

export const MODULE_GROUPS: ModuleGroup[] = ["Operations", "AI & Analysis", "Toolkits", "Business"];

export const MODULES: ModuleMeta[] = [
  {
    id: "soc-dashboard",
    label: "SOC Dashboard",
    description: "Live command overview — counters, heatmaps, timeline and alert feed.",
    route: "/dashboard",
    icon: LayoutDashboard,
    shortcut: "d",
    group: "Operations",
    phase: "P2",
    keywords: ["dashboard", "soc", "alerts", "overview", "home", "metrics"],
  },
  {
    id: "threat-intel",
    label: "Threat Intelligence",
    description: "Interactive globe with live attack arcs, heatmap and intel feed.",
    route: "/threat-intel",
    icon: Globe,
    shortcut: "g",
    group: "Operations",
    phase: "P2",
    keywords: ["globe", "threat", "intel", "arcs", "cve", "darkweb", "map"],
  },
  {
    id: "network-detection",
    label: "Network Detection",
    description: "Streaming packets, protocol breakdown, topology and suspicious IPs.",
    route: "/network",
    icon: Network,
    group: "Operations",
    phase: "P2",
    keywords: ["network", "packets", "ids", "protocol", "topology", "ip", "ddos"],
  },
  {
    id: "attack-graph",
    label: "Attack Graph",
    description: "3D visualization of devices, attack paths and lateral movement.",
    route: "/attack-graph",
    icon: Share2,
    group: "Operations",
    phase: "P2",
    keywords: ["graph", "3d", "nodes", "lateral", "path", "compromise"],
  },
  {
    id: "attack-simulator",
    label: "Attack Simulator",
    description: "Educational mode — launch simulated attacks and watch defenses respond.",
    route: "/attack-simulator",
    icon: Crosshair,
    group: "Operations",
    phase: "P5",
    keywords: ["simulator", "sql injection", "phishing", "ransomware", "education"],
  },
  {
    id: "ai-analyst",
    label: "AI Analyst",
    description: "Chat with the Sentinel AI — explain alerts, write rules, diagram attacks.",
    route: "/analyst",
    icon: Bot,
    shortcut: "a",
    group: "AI & Analysis",
    phase: "P3",
    keywords: ["chat", "ai", "analyst", "yara", "firewall", "assistant", "ask"],
  },
  {
    id: "incident-response",
    label: "Incident Response",
    description: "Auto-generated timelines, root cause, MITRE mapping and PDF reports.",
    route: "/incident-response",
    icon: Siren,
    group: "AI & Analysis",
    phase: "P3",
    keywords: ["incident", "response", "report", "pdf", "mitre", "root cause"],
  },
  {
    id: "threat-hunting",
    label: "Threat Hunting",
    description: "Natural-language and IOC search across the entire event store.",
    route: "/hunting",
    icon: Search,
    group: "AI & Analysis",
    phase: "P3",
    keywords: ["hunting", "search", "ioc", "query", "beaconing", "investigate"],
  },
  {
    id: "malware-analyzer",
    label: "Malware Analyzer",
    description: "Upload a file for client-side hashing, strings, entropy and risk scoring.",
    route: "/malware",
    icon: Bug,
    group: "AI & Analysis",
    phase: "P4",
    keywords: ["malware", "sandbox", "yara", "hash", "strings", "entropy", "upload"],
  },
  {
    id: "phishing-detector",
    label: "Phishing Detector",
    description: "Score emails, URLs and SMS for phishing indicators and spoofing.",
    route: "/phishing",
    icon: MailWarning,
    group: "AI & Analysis",
    phase: "P4",
    keywords: ["phishing", "email", "url", "spoof", "smishing", "confidence"],
  },
  {
    id: "password-center",
    label: "Password Center",
    description: "Entropy, crack-time estimates and strength recommendations.",
    route: "/password",
    icon: KeyRound,
    group: "AI & Analysis",
    phase: "P4",
    keywords: ["password", "entropy", "strength", "crack", "security"],
  },
  {
    id: "deepfake-detection",
    label: "Deepfake Detection",
    description: "Authenticity scoring for images, audio and video uploads.",
    route: "/deepfake",
    icon: ScanFace,
    group: "AI & Analysis",
    phase: "P4",
    keywords: ["deepfake", "image", "audio", "video", "authenticity", "forensics"],
  },
  {
    id: "vulnerability-scanner",
    label: "Vulnerability Scanner",
    description: "Scan assets for open ports, weak configs and exposed services.",
    route: "/vulnerability",
    icon: ShieldAlert,
    group: "AI & Analysis",
    phase: "P4",
    keywords: ["vulnerability", "scan", "ports", "cve", "remediation", "exposure"],
  },
  {
    id: "forensics",
    label: "Forensics Toolkit",
    description: "Memory, disk and event-log analysis with chain-of-custody tracking.",
    route: "/forensics",
    icon: Fingerprint,
    group: "Toolkits",
    phase: "P5",
    keywords: ["forensics", "memory", "disk", "logs", "custody", "evidence"],
  },
  {
    id: "secure-chat",
    label: "Secure Chat",
    description: "Demo end-to-end encrypted messaging with self-destruct messages.",
    route: "/secure-chat",
    icon: MessageSquareLock,
    group: "Toolkits",
    phase: "P5",
    keywords: ["chat", "encrypted", "e2e", "messaging", "self-destruct"],
  },
  {
    id: "automation",
    label: "AI Automation",
    description: "Drag-and-drop playbook builder that executes against the simulation.",
    route: "/automation",
    icon: Workflow,
    group: "Toolkits",
    phase: "P5",
    keywords: ["automation", "workflow", "playbook", "react flow", "triggers"],
  },
  {
    id: "compliance",
    label: "Compliance Center",
    description: "Generate reports for ISO 27001, NIST, PCI DSS, HIPAA and more.",
    route: "/compliance",
    icon: FileCheck,
    group: "Toolkits",
    phase: "P5",
    keywords: ["compliance", "iso", "nist", "gdpr", "hipaa", "report"],
  },
  {
    id: "security-score",
    label: "Security Score",
    description: "Aggregate posture, attack readiness and risk trend.",
    route: "/security-score",
    icon: Gauge,
    group: "Business",
    phase: "P5",
    keywords: ["score", "posture", "readiness", "trend", "rating"],
  },
  {
    id: "risk-prediction",
    label: "Risk Prediction",
    description: "Simulated ML forecasts — likely attacks, assets at risk, business impact.",
    route: "/risk",
    icon: TrendingUp,
    group: "Business",
    phase: "P5",
    keywords: ["risk", "prediction", "ml", "forecast", "likelihood", "impact"],
  },
  {
    id: "executive-dashboard",
    label: "Executive Dashboard",
    description: "Financial risk, security score, attack trends and ROI for leadership.",
    route: "/executive",
    icon: BarChart3,
    group: "Business",
    phase: "P5",
    keywords: ["executive", "roi", "financial", "board", "business"],
  },
];

export const MODULE_BY_ID: Record<string, ModuleMeta> = Object.fromEntries(
  MODULES.map((m) => [m.id, m]),
);
